[package]
name = "pore"
version = "0.1.0"
authors = ["Josh Gao <jmgao@google.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
lazy_static = "1.3.0"

log = "0.4"
failure = "0.1"
futures-preview = "0.3.0-alpha.14"
indoc = "0.3"

serde = "1.0"
serde_derive = "1.0"
toml = "0.5"
quick-xml = "0.14.0"
minidom = "0.10.0"

clap = "2.32"
maplit = "1.0"

dirs = "1.0"
shellexpand = "1.0"
pathdiff = "0.1"
url = "1.7"

git2 = "0.8"

console = "0.7"
indicatif = "0.11"

tracing_facade = "0.1"
tracing_chromium = "0.1"
